### PR TITLE
Added active cases

### PR DESCRIPTION
**Pull request by mgubis**
Active cases calculation has been added to import.py. You need to have following files together with import.py:

time_series_covid19_confirmed_global.csv
time_series_covid19_deaths_global.csv
time_series_covid19_recovered_global.csv

Files were added to .gitignore. Please create the link to:

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv
and
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv

Active cases are part of the cases.js - so there should be no change in your "update" process necessary.

### CODE REVIEW

**Comment by martinadamek** [comment]
Thanks a lot. As your contributions shows how unprepared my code was ;-), I have added you to contributors and merged your code to `activecases` branch. I will make some changes in master and rebase your branch to reflect them.

**Comment by mgubis** [comment]
Thanks for feedback. No worries, it was easy to refactor the code.
I must admit I am bit unfamiliar with git/github (we are using SVN for our projects). I thought you have created activecases branch here, but I couldn't find it. Have you created it only in your local clone? Also, rebasing my branch shouldn't end in modifying master ... so the question is, will my changes be visible via github.io (since I think it is hooked to master branch)?
Sorry for silly questions and thanks for your time.

**Comment by martinadamek** [comment]
Sorry, it was local only. Now it's pushed to repo.
I did it this way so I can easier test my changes (already done one - switching to subbmudule and not using links to files from data repo).
I think it will be much easier for me to test my changes than messing with forks. That means this pull request would be not needed anymore.

**Comment by martinadamek** [comment]
I am mesing with those branches again, so hold on please.

**Comment by martinadamek** [comment]
Branch merged to master. Closing this one.

**Pull request closed without merging**
